/*
 * generated by Xtext 2.29.0
 */
package org.xtext.example.mydsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.sparrow.ui.internal.SparrowActivator;

public class SparrowUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return SparrowActivator.getInstance().getInjector("org.xtext.example.mydsl.Sparrow");
	}

}
