/*
 * generated by Xtext 2.29.0
 */
package org.xtext.example.mydsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class SparrowUiModule extends AbstractSparrowUiModule {

	public SparrowUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
