/**
 * generated by Xtext 2.29.0
 */
package org.xtext.example.mydsl.sparrow.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.mydsl.sparrow.SparrowPackage;
import org.xtext.example.mydsl.sparrow.changeExpression;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>change Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class changeExpressionImpl extends trueOperationImpl implements changeExpression
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected changeExpressionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SparrowPackage.Literals.CHANGE_EXPRESSION;
  }

} //changeExpressionImpl
