/**
 * generated by Xtext 2.29.0
 */
package org.xtext.example.mydsl.sparrow.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.mydsl.sparrow.SparrowPackage;
import org.xtext.example.mydsl.sparrow.everyMessage;
import org.xtext.example.mydsl.sparrow.messageExpression;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>message Expression</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.sparrow.impl.messageExpressionImpl#getEverymassage <em>Everymassage</em>}</li>
 * </ul>
 *
 * @generated
 */
public class messageExpressionImpl extends MinimalEObjectImpl.Container implements messageExpression
{
  /**
   * The cached value of the '{@link #getEverymassage() <em>Everymassage</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEverymassage()
   * @generated
   * @ordered
   */
  protected EList<everyMessage> everymassage;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected messageExpressionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SparrowPackage.Literals.MESSAGE_EXPRESSION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<everyMessage> getEverymassage()
  {
    if (everymassage == null)
    {
      everymassage = new EObjectContainmentEList<everyMessage>(everyMessage.class, this, SparrowPackage.MESSAGE_EXPRESSION__EVERYMASSAGE);
    }
    return everymassage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case SparrowPackage.MESSAGE_EXPRESSION__EVERYMASSAGE:
        return ((InternalEList<?>)getEverymassage()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SparrowPackage.MESSAGE_EXPRESSION__EVERYMASSAGE:
        return getEverymassage();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SparrowPackage.MESSAGE_EXPRESSION__EVERYMASSAGE:
        getEverymassage().clear();
        getEverymassage().addAll((Collection<? extends everyMessage>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SparrowPackage.MESSAGE_EXPRESSION__EVERYMASSAGE:
        getEverymassage().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SparrowPackage.MESSAGE_EXPRESSION__EVERYMASSAGE:
        return everymassage != null && !everymassage.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //messageExpressionImpl
