/**
 * generated by Xtext 2.29.0
 */
package org.xtext.example.mydsl.sparrow.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.mydsl.sparrow.SparrowPackage;
import org.xtext.example.mydsl.sparrow.Timepoint;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Timepoint</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class TimepointImpl extends TrueConditionImpl implements Timepoint
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TimepointImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SparrowPackage.Literals.TIMEPOINT;
  }

} //TimepointImpl
