/**
 * generated by Xtext 2.29.0
 */
package org.xtext.example.mydsl.sparrow.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.mydsl.sparrow.AndOrOperationLink;
import org.xtext.example.mydsl.sparrow.FailResult;
import org.xtext.example.mydsl.sparrow.Group;
import org.xtext.example.mydsl.sparrow.OperateLink;
import org.xtext.example.mydsl.sparrow.SparrowPackage;
import org.xtext.example.mydsl.sparrow.ThenOperation;
import org.xtext.example.mydsl.sparrow.Timepoint;
import org.xtext.example.mydsl.sparrow.TotalOperation;
import org.xtext.example.mydsl.sparrow.initExpressions;
import org.xtext.example.mydsl.sparrow.trueOperation;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Total Operation</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.sparrow.impl.TotalOperationImpl#getPerson <em>Person</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.sparrow.impl.TotalOperationImpl#getPerson2 <em>Person2</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.sparrow.impl.TotalOperationImpl#getFirstOperation <em>First Operation</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.sparrow.impl.TotalOperationImpl#getLinkOperation <em>Link Operation</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.sparrow.impl.TotalOperationImpl#getAndor <em>Andor</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.sparrow.impl.TotalOperationImpl#getTimePoint <em>Time Point</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.sparrow.impl.TotalOperationImpl#getFailresult <em>Failresult</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.sparrow.impl.TotalOperationImpl#getThenoperation <em>Thenoperation</em>}</li>
 * </ul>
 *
 * @generated
 */
public class TotalOperationImpl extends MinimalEObjectImpl.Container implements TotalOperation
{
  /**
   * The cached value of the '{@link #getPerson() <em>Person</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPerson()
   * @generated
   * @ordered
   */
  protected initExpressions person;

  /**
   * The cached value of the '{@link #getPerson2() <em>Person2</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPerson2()
   * @generated
   * @ordered
   */
  protected Group person2;

  /**
   * The cached value of the '{@link #getFirstOperation() <em>First Operation</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFirstOperation()
   * @generated
   * @ordered
   */
  protected trueOperation firstOperation;

  /**
   * The cached value of the '{@link #getLinkOperation() <em>Link Operation</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLinkOperation()
   * @generated
   * @ordered
   */
  protected OperateLink linkOperation;

  /**
   * The cached value of the '{@link #getAndor() <em>Andor</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAndor()
   * @generated
   * @ordered
   */
  protected EList<AndOrOperationLink> andor;

  /**
   * The cached value of the '{@link #getTimePoint() <em>Time Point</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTimePoint()
   * @generated
   * @ordered
   */
  protected Timepoint timePoint;

  /**
   * The cached value of the '{@link #getFailresult() <em>Failresult</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFailresult()
   * @generated
   * @ordered
   */
  protected FailResult failresult;

  /**
   * The cached value of the '{@link #getThenoperation() <em>Thenoperation</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getThenoperation()
   * @generated
   * @ordered
   */
  protected EList<ThenOperation> thenoperation;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TotalOperationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SparrowPackage.Literals.TOTAL_OPERATION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public initExpressions getPerson()
  {
    if (person != null && person.eIsProxy())
    {
      InternalEObject oldPerson = (InternalEObject)person;
      person = (initExpressions)eResolveProxy(oldPerson);
      if (person != oldPerson)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, SparrowPackage.TOTAL_OPERATION__PERSON, oldPerson, person));
      }
    }
    return person;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public initExpressions basicGetPerson()
  {
    return person;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPerson(initExpressions newPerson)
  {
    initExpressions oldPerson = person;
    person = newPerson;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SparrowPackage.TOTAL_OPERATION__PERSON, oldPerson, person));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Group getPerson2()
  {
    if (person2 != null && person2.eIsProxy())
    {
      InternalEObject oldPerson2 = (InternalEObject)person2;
      person2 = (Group)eResolveProxy(oldPerson2);
      if (person2 != oldPerson2)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, SparrowPackage.TOTAL_OPERATION__PERSON2, oldPerson2, person2));
      }
    }
    return person2;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Group basicGetPerson2()
  {
    return person2;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPerson2(Group newPerson2)
  {
    Group oldPerson2 = person2;
    person2 = newPerson2;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SparrowPackage.TOTAL_OPERATION__PERSON2, oldPerson2, person2));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public trueOperation getFirstOperation()
  {
    return firstOperation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetFirstOperation(trueOperation newFirstOperation, NotificationChain msgs)
  {
    trueOperation oldFirstOperation = firstOperation;
    firstOperation = newFirstOperation;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, SparrowPackage.TOTAL_OPERATION__FIRST_OPERATION, oldFirstOperation, newFirstOperation);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setFirstOperation(trueOperation newFirstOperation)
  {
    if (newFirstOperation != firstOperation)
    {
      NotificationChain msgs = null;
      if (firstOperation != null)
        msgs = ((InternalEObject)firstOperation).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - SparrowPackage.TOTAL_OPERATION__FIRST_OPERATION, null, msgs);
      if (newFirstOperation != null)
        msgs = ((InternalEObject)newFirstOperation).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - SparrowPackage.TOTAL_OPERATION__FIRST_OPERATION, null, msgs);
      msgs = basicSetFirstOperation(newFirstOperation, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SparrowPackage.TOTAL_OPERATION__FIRST_OPERATION, newFirstOperation, newFirstOperation));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public OperateLink getLinkOperation()
  {
    if (linkOperation != null && linkOperation.eIsProxy())
    {
      InternalEObject oldLinkOperation = (InternalEObject)linkOperation;
      linkOperation = (OperateLink)eResolveProxy(oldLinkOperation);
      if (linkOperation != oldLinkOperation)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, SparrowPackage.TOTAL_OPERATION__LINK_OPERATION, oldLinkOperation, linkOperation));
      }
    }
    return linkOperation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public OperateLink basicGetLinkOperation()
  {
    return linkOperation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setLinkOperation(OperateLink newLinkOperation)
  {
    OperateLink oldLinkOperation = linkOperation;
    linkOperation = newLinkOperation;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SparrowPackage.TOTAL_OPERATION__LINK_OPERATION, oldLinkOperation, linkOperation));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<AndOrOperationLink> getAndor()
  {
    if (andor == null)
    {
      andor = new EObjectContainmentEList<AndOrOperationLink>(AndOrOperationLink.class, this, SparrowPackage.TOTAL_OPERATION__ANDOR);
    }
    return andor;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Timepoint getTimePoint()
  {
    return timePoint;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetTimePoint(Timepoint newTimePoint, NotificationChain msgs)
  {
    Timepoint oldTimePoint = timePoint;
    timePoint = newTimePoint;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, SparrowPackage.TOTAL_OPERATION__TIME_POINT, oldTimePoint, newTimePoint);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTimePoint(Timepoint newTimePoint)
  {
    if (newTimePoint != timePoint)
    {
      NotificationChain msgs = null;
      if (timePoint != null)
        msgs = ((InternalEObject)timePoint).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - SparrowPackage.TOTAL_OPERATION__TIME_POINT, null, msgs);
      if (newTimePoint != null)
        msgs = ((InternalEObject)newTimePoint).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - SparrowPackage.TOTAL_OPERATION__TIME_POINT, null, msgs);
      msgs = basicSetTimePoint(newTimePoint, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SparrowPackage.TOTAL_OPERATION__TIME_POINT, newTimePoint, newTimePoint));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public FailResult getFailresult()
  {
    return failresult;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetFailresult(FailResult newFailresult, NotificationChain msgs)
  {
    FailResult oldFailresult = failresult;
    failresult = newFailresult;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, SparrowPackage.TOTAL_OPERATION__FAILRESULT, oldFailresult, newFailresult);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setFailresult(FailResult newFailresult)
  {
    if (newFailresult != failresult)
    {
      NotificationChain msgs = null;
      if (failresult != null)
        msgs = ((InternalEObject)failresult).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - SparrowPackage.TOTAL_OPERATION__FAILRESULT, null, msgs);
      if (newFailresult != null)
        msgs = ((InternalEObject)newFailresult).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - SparrowPackage.TOTAL_OPERATION__FAILRESULT, null, msgs);
      msgs = basicSetFailresult(newFailresult, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SparrowPackage.TOTAL_OPERATION__FAILRESULT, newFailresult, newFailresult));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<ThenOperation> getThenoperation()
  {
    if (thenoperation == null)
    {
      thenoperation = new EObjectContainmentEList<ThenOperation>(ThenOperation.class, this, SparrowPackage.TOTAL_OPERATION__THENOPERATION);
    }
    return thenoperation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case SparrowPackage.TOTAL_OPERATION__FIRST_OPERATION:
        return basicSetFirstOperation(null, msgs);
      case SparrowPackage.TOTAL_OPERATION__ANDOR:
        return ((InternalEList<?>)getAndor()).basicRemove(otherEnd, msgs);
      case SparrowPackage.TOTAL_OPERATION__TIME_POINT:
        return basicSetTimePoint(null, msgs);
      case SparrowPackage.TOTAL_OPERATION__FAILRESULT:
        return basicSetFailresult(null, msgs);
      case SparrowPackage.TOTAL_OPERATION__THENOPERATION:
        return ((InternalEList<?>)getThenoperation()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SparrowPackage.TOTAL_OPERATION__PERSON:
        if (resolve) return getPerson();
        return basicGetPerson();
      case SparrowPackage.TOTAL_OPERATION__PERSON2:
        if (resolve) return getPerson2();
        return basicGetPerson2();
      case SparrowPackage.TOTAL_OPERATION__FIRST_OPERATION:
        return getFirstOperation();
      case SparrowPackage.TOTAL_OPERATION__LINK_OPERATION:
        if (resolve) return getLinkOperation();
        return basicGetLinkOperation();
      case SparrowPackage.TOTAL_OPERATION__ANDOR:
        return getAndor();
      case SparrowPackage.TOTAL_OPERATION__TIME_POINT:
        return getTimePoint();
      case SparrowPackage.TOTAL_OPERATION__FAILRESULT:
        return getFailresult();
      case SparrowPackage.TOTAL_OPERATION__THENOPERATION:
        return getThenoperation();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SparrowPackage.TOTAL_OPERATION__PERSON:
        setPerson((initExpressions)newValue);
        return;
      case SparrowPackage.TOTAL_OPERATION__PERSON2:
        setPerson2((Group)newValue);
        return;
      case SparrowPackage.TOTAL_OPERATION__FIRST_OPERATION:
        setFirstOperation((trueOperation)newValue);
        return;
      case SparrowPackage.TOTAL_OPERATION__LINK_OPERATION:
        setLinkOperation((OperateLink)newValue);
        return;
      case SparrowPackage.TOTAL_OPERATION__ANDOR:
        getAndor().clear();
        getAndor().addAll((Collection<? extends AndOrOperationLink>)newValue);
        return;
      case SparrowPackage.TOTAL_OPERATION__TIME_POINT:
        setTimePoint((Timepoint)newValue);
        return;
      case SparrowPackage.TOTAL_OPERATION__FAILRESULT:
        setFailresult((FailResult)newValue);
        return;
      case SparrowPackage.TOTAL_OPERATION__THENOPERATION:
        getThenoperation().clear();
        getThenoperation().addAll((Collection<? extends ThenOperation>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SparrowPackage.TOTAL_OPERATION__PERSON:
        setPerson((initExpressions)null);
        return;
      case SparrowPackage.TOTAL_OPERATION__PERSON2:
        setPerson2((Group)null);
        return;
      case SparrowPackage.TOTAL_OPERATION__FIRST_OPERATION:
        setFirstOperation((trueOperation)null);
        return;
      case SparrowPackage.TOTAL_OPERATION__LINK_OPERATION:
        setLinkOperation((OperateLink)null);
        return;
      case SparrowPackage.TOTAL_OPERATION__ANDOR:
        getAndor().clear();
        return;
      case SparrowPackage.TOTAL_OPERATION__TIME_POINT:
        setTimePoint((Timepoint)null);
        return;
      case SparrowPackage.TOTAL_OPERATION__FAILRESULT:
        setFailresult((FailResult)null);
        return;
      case SparrowPackage.TOTAL_OPERATION__THENOPERATION:
        getThenoperation().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SparrowPackage.TOTAL_OPERATION__PERSON:
        return person != null;
      case SparrowPackage.TOTAL_OPERATION__PERSON2:
        return person2 != null;
      case SparrowPackage.TOTAL_OPERATION__FIRST_OPERATION:
        return firstOperation != null;
      case SparrowPackage.TOTAL_OPERATION__LINK_OPERATION:
        return linkOperation != null;
      case SparrowPackage.TOTAL_OPERATION__ANDOR:
        return andor != null && !andor.isEmpty();
      case SparrowPackage.TOTAL_OPERATION__TIME_POINT:
        return timePoint != null;
      case SparrowPackage.TOTAL_OPERATION__FAILRESULT:
        return failresult != null;
      case SparrowPackage.TOTAL_OPERATION__THENOPERATION:
        return thenoperation != null && !thenoperation.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //TotalOperationImpl
