/*
 * generated by Xtext 2.29.0
 */
package org.xtext.example.mydsl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.mydsl.parser.antlr.internal.InternalSparrowParser;
import org.xtext.example.mydsl.services.SparrowGrammarAccess;

public class SparrowParser extends AbstractAntlrParser {

	@Inject
	private SparrowGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalSparrowParser createParser(XtextTokenStream stream) {
		return new InternalSparrowParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public SparrowGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SparrowGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
