/**
 * generated by Xtext 2.29.0
 */
package org.xtext.example.mydsl.sparrow;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Addition Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.sparrow.SparrowPackage#getAdditionExpression()
 * @model
 * @generated
 */
public interface AdditionExpression extends ManyRuleExpression
{
} // AdditionExpression
