/**
 * generated by Xtext 2.29.0
 */
package org.xtext.example.mydsl.sparrow;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>And Or Operation Link</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.sparrow.AndOrOperationLink#getLink <em>Link</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.sparrow.AndOrOperationLink#getFirstOperation <em>First Operation</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.sparrow.AndOrOperationLink#getLinkOperation <em>Link Operation</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.sparrow.SparrowPackage#getAndOrOperationLink()
 * @model
 * @generated
 */
public interface AndOrOperationLink extends EObject
{
  /**
   * Returns the value of the '<em><b>Link</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Link</em>' attribute.
   * @see #setLink(String)
   * @see org.xtext.example.mydsl.sparrow.SparrowPackage#getAndOrOperationLink_Link()
   * @model
   * @generated
   */
  String getLink();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.sparrow.AndOrOperationLink#getLink <em>Link</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Link</em>' attribute.
   * @see #getLink()
   * @generated
   */
  void setLink(String value);

  /**
   * Returns the value of the '<em><b>First Operation</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>First Operation</em>' containment reference.
   * @see #setFirstOperation(trueOperation)
   * @see org.xtext.example.mydsl.sparrow.SparrowPackage#getAndOrOperationLink_FirstOperation()
   * @model containment="true"
   * @generated
   */
  trueOperation getFirstOperation();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.sparrow.AndOrOperationLink#getFirstOperation <em>First Operation</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>First Operation</em>' containment reference.
   * @see #getFirstOperation()
   * @generated
   */
  void setFirstOperation(trueOperation value);

  /**
   * Returns the value of the '<em><b>Link Operation</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Link Operation</em>' reference.
   * @see #setLinkOperation(OperateLink)
   * @see org.xtext.example.mydsl.sparrow.SparrowPackage#getAndOrOperationLink_LinkOperation()
   * @model
   * @generated
   */
  OperateLink getLinkOperation();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.sparrow.AndOrOperationLink#getLinkOperation <em>Link Operation</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Link Operation</em>' reference.
   * @see #getLinkOperation()
   * @generated
   */
  void setLinkOperation(OperateLink value);

} // AndOrOperationLink
