/**
 * generated by Xtext 2.29.0
 */
package org.xtext.example.mydsl.sparrow;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>change Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.sparrow.SparrowPackage#getchangeExpression()
 * @model
 * @generated
 */
public interface changeExpression extends trueOperation
{
} // changeExpression
