/**
 * generated by Xtext 2.29.0
 */
package org.xtext.example.mydsl.sparrow;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>change Contract</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.sparrow.changeContract#getChangeResult <em>Change Result</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.sparrow.SparrowPackage#getchangeContract()
 * @model
 * @generated
 */
public interface changeContract extends changeExpression
{
  /**
   * Returns the value of the '<em><b>Change Result</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Change Result</em>' attribute.
   * @see #setChangeResult(String)
   * @see org.xtext.example.mydsl.sparrow.SparrowPackage#getchangeContract_ChangeResult()
   * @model
   * @generated
   */
  String getChangeResult();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.sparrow.changeContract#getChangeResult <em>Change Result</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Change Result</em>' attribute.
   * @see #getChangeResult()
   * @generated
   */
  void setChangeResult(String value);

} // changeContract
