/**
 * generated by Xtext 2.29.0
 */
package org.xtext.example.mydsl.sparrow;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>init Expressions</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.sparrow.initExpressions#getSubtype <em>Subtype</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.sparrow.initExpressions#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.sparrow.initExpressions#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.sparrow.SparrowPackage#getinitExpressions()
 * @model
 * @generated
 */
public interface initExpressions extends EObject
{
  /**
   * Returns the value of the '<em><b>Subtype</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Subtype</em>' reference.
   * @see #setSubtype(Subject)
   * @see org.xtext.example.mydsl.sparrow.SparrowPackage#getinitExpressions_Subtype()
   * @model
   * @generated
   */
  Subject getSubtype();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.sparrow.initExpressions#getSubtype <em>Subtype</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Subtype</em>' reference.
   * @see #getSubtype()
   * @generated
   */
  void setSubtype(Subject value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.mydsl.sparrow.SparrowPackage#getinitExpressions_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.sparrow.initExpressions#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Value</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.sparrow.Value}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' containment reference list.
   * @see org.xtext.example.mydsl.sparrow.SparrowPackage#getinitExpressions_Value()
   * @model containment="true"
   * @generated
   */
  EList<Value> getValue();

} // initExpressions
