/**
 * generated by Xtext 2.29.0
 */
package org.xtext.example.mydsl.sparrow;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>is Time</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.sparrow.isTime#getExpression <em>Expression</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.sparrow.isTime#getValue <em>Value</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.sparrow.isTime#getSymbol <em>Symbol</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.sparrow.isTime#getDuration <em>Duration</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.sparrow.SparrowPackage#getisTime()
 * @model
 * @generated
 */
public interface isTime extends TrueCondition
{
  /**
   * Returns the value of the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expression</em>' containment reference.
   * @see #setExpression(MixExpression)
   * @see org.xtext.example.mydsl.sparrow.SparrowPackage#getisTime_Expression()
   * @model containment="true"
   * @generated
   */
  MixExpression getExpression();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.sparrow.isTime#getExpression <em>Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expression</em>' containment reference.
   * @see #getExpression()
   * @generated
   */
  void setExpression(MixExpression value);

  /**
   * Returns the value of the '<em><b>Value</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' reference.
   * @see #setValue(RuleExpression)
   * @see org.xtext.example.mydsl.sparrow.SparrowPackage#getisTime_Value()
   * @model
   * @generated
   */
  RuleExpression getValue();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.sparrow.isTime#getValue <em>Value</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' reference.
   * @see #getValue()
   * @generated
   */
  void setValue(RuleExpression value);

  /**
   * Returns the value of the '<em><b>Symbol</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Symbol</em>' attribute.
   * @see #setSymbol(String)
   * @see org.xtext.example.mydsl.sparrow.SparrowPackage#getisTime_Symbol()
   * @model
   * @generated
   */
  String getSymbol();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.sparrow.isTime#getSymbol <em>Symbol</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Symbol</em>' attribute.
   * @see #getSymbol()
   * @generated
   */
  void setSymbol(String value);

  /**
   * Returns the value of the '<em><b>Duration</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Duration</em>' containment reference.
   * @see #setDuration(Duration)
   * @see org.xtext.example.mydsl.sparrow.SparrowPackage#getisTime_Duration()
   * @model containment="true"
   * @generated
   */
  Duration getDuration();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.sparrow.isTime#getDuration <em>Duration</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Duration</em>' containment reference.
   * @see #getDuration()
   * @generated
   */
  void setDuration(Duration value);

} // isTime
