/**
 * generated by Xtext 2.29.0
 */
package org.xtext.example.mydsl.sparrow;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>is True</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.sparrow.isTrue#getCompare <em>Compare</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.sparrow.SparrowPackage#getisTrue()
 * @model
 * @generated
 */
public interface isTrue extends TrueCondition
{
  /**
   * Returns the value of the '<em><b>Compare</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Compare</em>' containment reference.
   * @see #setCompare(SingleExpression)
   * @see org.xtext.example.mydsl.sparrow.SparrowPackage#getisTrue_Compare()
   * @model containment="true"
   * @generated
   */
  SingleExpression getCompare();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.sparrow.isTrue#getCompare <em>Compare</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Compare</em>' containment reference.
   * @see #getCompare()
   * @generated
   */
  void setCompare(SingleExpression value);

} // isTrue
