/**
 * generated by Xtext 2.29.0
 */
package org.xtext.example.mydsl.sparrow;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>message Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.sparrow.messageExpression#getEverymassage <em>Everymassage</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.sparrow.SparrowPackage#getmessageExpression()
 * @model
 * @generated
 */
public interface messageExpression extends EObject
{
  /**
   * Returns the value of the '<em><b>Everymassage</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.sparrow.everyMessage}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Everymassage</em>' containment reference list.
   * @see org.xtext.example.mydsl.sparrow.SparrowPackage#getmessageExpression_Everymassage()
   * @model containment="true"
   * @generated
   */
  EList<everyMessage> getEverymassage();

} // messageExpression
