/**
 * generated by Xtext 2.29.0
 */
package org.xtext.example.mydsl.sparrow;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Object Express</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.sparrow.ObjectExpress#getObject <em>Object</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.sparrow.SparrowPackage#getObjectExpress()
 * @model
 * @generated
 */
public interface ObjectExpress extends ThingExpression
{
  /**
   * Returns the value of the '<em><b>Object</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Object</em>' reference.
   * @see #setObject(initExpressiono)
   * @see org.xtext.example.mydsl.sparrow.SparrowPackage#getObjectExpress_Object()
   * @model
   * @generated
   */
  initExpressiono getObject();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.sparrow.ObjectExpress#getObject <em>Object</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Object</em>' reference.
   * @see #getObject()
   * @generated
   */
  void setObject(initExpressiono value);

} // ObjectExpress
