/**
 * generated by Xtext 2.29.0
 */
package org.xtext.example.mydsl.sparrow;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Operate Link</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.sparrow.OperateLink#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.sparrow.OperateLink#getFirstOperation <em>First Operation</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.sparrow.OperateLink#getLinkOperation <em>Link Operation</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.sparrow.OperateLink#getAndOrLink <em>And Or Link</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.sparrow.SparrowPackage#getOperateLink()
 * @model
 * @generated
 */
public interface OperateLink extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.mydsl.sparrow.SparrowPackage#getOperateLink_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.sparrow.OperateLink#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>First Operation</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>First Operation</em>' containment reference.
   * @see #setFirstOperation(trueOperation)
   * @see org.xtext.example.mydsl.sparrow.SparrowPackage#getOperateLink_FirstOperation()
   * @model containment="true"
   * @generated
   */
  trueOperation getFirstOperation();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.sparrow.OperateLink#getFirstOperation <em>First Operation</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>First Operation</em>' containment reference.
   * @see #getFirstOperation()
   * @generated
   */
  void setFirstOperation(trueOperation value);

  /**
   * Returns the value of the '<em><b>Link Operation</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Link Operation</em>' reference.
   * @see #setLinkOperation(OperateLink)
   * @see org.xtext.example.mydsl.sparrow.SparrowPackage#getOperateLink_LinkOperation()
   * @model
   * @generated
   */
  OperateLink getLinkOperation();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.sparrow.OperateLink#getLinkOperation <em>Link Operation</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Link Operation</em>' reference.
   * @see #getLinkOperation()
   * @generated
   */
  void setLinkOperation(OperateLink value);

  /**
   * Returns the value of the '<em><b>And Or Link</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.sparrow.AndOrOperationLink}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>And Or Link</em>' containment reference list.
   * @see org.xtext.example.mydsl.sparrow.SparrowPackage#getOperateLink_AndOrLink()
   * @model containment="true"
   * @generated
   */
  EList<AndOrOperationLink> getAndOrLink();

} // OperateLink
