/**
 * generated by Xtext 2.29.0
 */
package org.xtext.example.mydsl.sparrow;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.sparrow.SparrowPackage
 * @generated
 */
public interface SparrowFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  SparrowFactory eINSTANCE = org.xtext.example.mydsl.sparrow.impl.SparrowFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Model</em>'.
   * @generated
   */
  Model createModel();

  /**
   * Returns a new object of class '<em>Require</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Require</em>'.
   * @generated
   */
  Require createRequire();

  /**
   * Returns a new object of class '<em>Initialize</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Initialize</em>'.
   * @generated
   */
  Initialize createInitialize();

  /**
   * Returns a new object of class '<em>init Expressions</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>init Expressions</em>'.
   * @generated
   */
  initExpressions createinitExpressions();

  /**
   * Returns a new object of class '<em>init Expressiono</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>init Expressiono</em>'.
   * @generated
   */
  initExpressiono createinitExpressiono();

  /**
   * Returns a new object of class '<em>Group</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Group</em>'.
   * @generated
   */
  Group createGroup();

  /**
   * Returns a new object of class '<em>Subject</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Subject</em>'.
   * @generated
   */
  Subject createSubject();

  /**
   * Returns a new object of class '<em>Subject Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Subject Expression</em>'.
   * @generated
   */
  SubjectExpression createSubjectExpression();

  /**
   * Returns a new object of class '<em>Contract Message</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Contract Message</em>'.
   * @generated
   */
  ContractMessage createContractMessage();

  /**
   * Returns a new object of class '<em>Message</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Message</em>'.
   * @generated
   */
  Message createMessage();

  /**
   * Returns a new object of class '<em>keyvalue</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>keyvalue</em>'.
   * @generated
   */
  keyvalue createkeyvalue();

  /**
   * Returns a new object of class '<em>Value</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Value</em>'.
   * @generated
   */
  Value createValue();

  /**
   * Returns a new object of class '<em>Duration</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Duration</em>'.
   * @generated
   */
  Duration createDuration();

  /**
   * Returns a new object of class '<em>Now</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Now</em>'.
   * @generated
   */
  Now createNow();

  /**
   * Returns a new object of class '<em>This String</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>This String</em>'.
   * @generated
   */
  ThisString createThisString();

  /**
   * Returns a new object of class '<em>Address</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Address</em>'.
   * @generated
   */
  Address createAddress();

  /**
   * Returns a new object of class '<em>All Number</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>All Number</em>'.
   * @generated
   */
  AllNumber createAllNumber();

  /**
   * Returns a new object of class '<em>This Decimal</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>This Decimal</em>'.
   * @generated
   */
  ThisDecimal createThisDecimal();

  /**
   * Returns a new object of class '<em>url</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>url</em>'.
   * @generated
   */
  url createurl();

  /**
   * Returns a new object of class '<em>This Boolean</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>This Boolean</em>'.
   * @generated
   */
  ThisBoolean createThisBoolean();

  /**
   * Returns a new object of class '<em>This Date</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>This Date</em>'.
   * @generated
   */
  ThisDate createThisDate();

  /**
   * Returns a new object of class '<em>Right</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Right</em>'.
   * @generated
   */
  Right createRight();

  /**
   * Returns a new object of class '<em>DATE</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>DATE</em>'.
   * @generated
   */
  DATE createDATE();

  /**
   * Returns a new object of class '<em>Object</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Object</em>'.
   * @generated
   */
  Object createObject();

  /**
   * Returns a new object of class '<em>Object Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Object Expression</em>'.
   * @generated
   */
  ObjectExpression createObjectExpression();

  /**
   * Returns a new object of class '<em>Condition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Condition</em>'.
   * @generated
   */
  Condition createCondition();

  /**
   * Returns a new object of class '<em>Condition Link</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Condition Link</em>'.
   * @generated
   */
  ConditionLink createConditionLink();

  /**
   * Returns a new object of class '<em>And Or Condition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>And Or Condition</em>'.
   * @generated
   */
  AndOrCondition createAndOrCondition();

  /**
   * Returns a new object of class '<em>Operation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Operation</em>'.
   * @generated
   */
  Operation createOperation();

  /**
   * Returns a new object of class '<em>Operate Link</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Operate Link</em>'.
   * @generated
   */
  OperateLink createOperateLink();

  /**
   * Returns a new object of class '<em>Rule Structure</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Rule Structure</em>'.
   * @generated
   */
  RuleStructure createRuleStructure();

  /**
   * Returns a new object of class '<em>Many Rule Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Many Rule Expression</em>'.
   * @generated
   */
  ManyRuleExpression createManyRuleExpression();

  /**
   * Returns a new object of class '<em>Parallel Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Parallel Expression</em>'.
   * @generated
   */
  ParallelExpression createParallelExpression();

  /**
   * Returns a new object of class '<em>Exclusive Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Exclusive Expression</em>'.
   * @generated
   */
  ExclusiveExpression createExclusiveExpression();

  /**
   * Returns a new object of class '<em>Regular Rule Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Regular Rule Expression</em>'.
   * @generated
   */
  RegularRuleExpression createRegularRuleExpression();

  /**
   * Returns a new object of class '<em>Addition Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Addition Expression</em>'.
   * @generated
   */
  AdditionExpression createAdditionExpression();

  /**
   * Returns a new object of class '<em>Total Condition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Total Condition</em>'.
   * @generated
   */
  TotalCondition createTotalCondition();

  /**
   * Returns a new object of class '<em>Single Link Condition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Single Link Condition</em>'.
   * @generated
   */
  SingleLinkCondition createSingleLinkCondition();

  /**
   * Returns a new object of class '<em>Total Operation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Total Operation</em>'.
   * @generated
   */
  TotalOperation createTotalOperation();

  /**
   * Returns a new object of class '<em>And Or Operation Link</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>And Or Operation Link</em>'.
   * @generated
   */
  AndOrOperationLink createAndOrOperationLink();

  /**
   * Returns a new object of class '<em>Then Operation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Then Operation</em>'.
   * @generated
   */
  ThenOperation createThenOperation();

  /**
   * Returns a new object of class '<em>Total Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Total Expression</em>'.
   * @generated
   */
  TotalExpression createTotalExpression();

  /**
   * Returns a new object of class '<em>Else Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Else Expression</em>'.
   * @generated
   */
  ElseExpression createElseExpression();

  /**
   * Returns a new object of class '<em>Rule Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Rule Expression</em>'.
   * @generated
   */
  RuleExpression createRuleExpression();

  /**
   * Returns a new object of class '<em>set Date Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>set Date Expression</em>'.
   * @generated
   */
  setDateExpression createsetDateExpression();

  /**
   * Returns a new object of class '<em>Sub Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Sub Expression</em>'.
   * @generated
   */
  SubExpression createSubExpression();

  /**
   * Returns a new object of class '<em>Fail Result</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Fail Result</em>'.
   * @generated
   */
  FailResult createFailResult();

  /**
   * Returns a new object of class '<em>Timepoint</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Timepoint</em>'.
   * @generated
   */
  Timepoint createTimepoint();

  /**
   * Returns a new object of class '<em>Within Point</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Within Point</em>'.
   * @generated
   */
  WithinPoint createWithinPoint();

  /**
   * Returns a new object of class '<em>Before Point</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Before Point</em>'.
   * @generated
   */
  BeforePoint createBeforePoint();

  /**
   * Returns a new object of class '<em>Single Condition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Single Condition</em>'.
   * @generated
   */
  SingleCondition createSingleCondition();

  /**
   * Returns a new object of class '<em>True Condition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>True Condition</em>'.
   * @generated
   */
  TrueCondition createTrueCondition();

  /**
   * Returns a new object of class '<em>Compare String</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Compare String</em>'.
   * @generated
   */
  CompareString createCompareString();

  /**
   * Returns a new object of class '<em>Time Sub</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Time Sub</em>'.
   * @generated
   */
  TimeSub createTimeSub();

  /**
   * Returns a new object of class '<em>is Time</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>is Time</em>'.
   * @generated
   */
  isTime createisTime();

  /**
   * Returns a new object of class '<em>logic</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>logic</em>'.
   * @generated
   */
  logic createlogic();

  /**
   * Returns a new object of class '<em>is True</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>is True</em>'.
   * @generated
   */
  isTrue createisTrue();

  /**
   * Returns a new object of class '<em>is Done</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>is Done</em>'.
   * @generated
   */
  isDone createisDone();

  /**
   * Returns a new object of class '<em>check Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>check Expression</em>'.
   * @generated
   */
  checkExpression createcheckExpression();

  /**
   * Returns a new object of class '<em>Mix Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Mix Expression</em>'.
   * @generated
   */
  MixExpression createMixExpression();

  /**
   * Returns a new object of class '<em>Other Mix Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Other Mix Expression</em>'.
   * @generated
   */
  OtherMixExpression createOtherMixExpression();

  /**
   * Returns a new object of class '<em>Single Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Single Expression</em>'.
   * @generated
   */
  SingleExpression createSingleExpression();

  /**
   * Returns a new object of class '<em>Period Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Period Expression</em>'.
   * @generated
   */
  PeriodExpression createPeriodExpression();

  /**
   * Returns a new object of class '<em>Get Period Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Get Period Expression</em>'.
   * @generated
   */
  GetPeriodExpression createGetPeriodExpression();

  /**
   * Returns a new object of class '<em>Rule Time Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Rule Time Expression</em>'.
   * @generated
   */
  RuleTimeExpression createRuleTimeExpression();

  /**
   * Returns a new object of class '<em>Other Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Other Expression</em>'.
   * @generated
   */
  OtherExpression createOtherExpression();

  /**
   * Returns a new object of class '<em>String Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>String Expression</em>'.
   * @generated
   */
  StringExpression createStringExpression();

  /**
   * Returns a new object of class '<em>Float Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Float Expression</em>'.
   * @generated
   */
  FloatExpression createFloatExpression();

  /**
   * Returns a new object of class '<em>Person Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Person Expression</em>'.
   * @generated
   */
  PersonExpression createPersonExpression();

  /**
   * Returns a new object of class '<em>Regular Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Regular Expression</em>'.
   * @generated
   */
  RegularExpression createRegularExpression();

  /**
   * Returns a new object of class '<em>Thing Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Thing Expression</em>'.
   * @generated
   */
  ThingExpression createThingExpression();

  /**
   * Returns a new object of class '<em>Subject Express</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Subject Express</em>'.
   * @generated
   */
  SubjectExpress createSubjectExpress();

  /**
   * Returns a new object of class '<em>Object Express</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Object Express</em>'.
   * @generated
   */
  ObjectExpress createObjectExpress();

  /**
   * Returns a new object of class '<em>true Operation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>true Operation</em>'.
   * @generated
   */
  trueOperation createtrueOperation();

  /**
   * Returns a new object of class '<em>message Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>message Expression</em>'.
   * @generated
   */
  messageExpression createmessageExpression();

  /**
   * Returns a new object of class '<em>every Message</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>every Message</em>'.
   * @generated
   */
  everyMessage createeveryMessage();

  /**
   * Returns a new object of class '<em>transfer Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>transfer Expression</em>'.
   * @generated
   */
  transferExpression createtransferExpression();

  /**
   * Returns a new object of class '<em>change Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>change Expression</em>'.
   * @generated
   */
  changeExpression createchangeExpression();

  /**
   * Returns a new object of class '<em>change String</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>change String</em>'.
   * @generated
   */
  changeString createchangeString();

  /**
   * Returns a new object of class '<em>otherchange</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>otherchange</em>'.
   * @generated
   */
  otherchange createotherchange();

  /**
   * Returns a new object of class '<em>change Contract</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>change Contract</em>'.
   * @generated
   */
  changeContract createchangeContract();

  /**
   * Returns a new object of class '<em>change Rule</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>change Rule</em>'.
   * @generated
   */
  changeRule createchangeRule();

  /**
   * Returns a new object of class '<em>change Other</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>change Other</em>'.
   * @generated
   */
  changeOther createchangeOther();

  /**
   * Returns a new object of class '<em>change Address</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>change Address</em>'.
   * @generated
   */
  changeAddress createchangeAddress();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  SparrowPackage getSparrowPackage();

} //SparrowFactory
