/**
 * generated by Xtext 2.29.0
 */
package org.xtext.example.mydsl.sparrow;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Subject Express</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.sparrow.SubjectExpress#getSubject <em>Subject</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.sparrow.SparrowPackage#getSubjectExpress()
 * @model
 * @generated
 */
public interface SubjectExpress extends ThingExpression
{
  /**
   * Returns the value of the '<em><b>Subject</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Subject</em>' reference.
   * @see #setSubject(initExpressions)
   * @see org.xtext.example.mydsl.sparrow.SparrowPackage#getSubjectExpress_Subject()
   * @model
   * @generated
   */
  initExpressions getSubject();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.sparrow.SubjectExpress#getSubject <em>Subject</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Subject</em>' reference.
   * @see #getSubject()
   * @generated
   */
  void setSubject(initExpressions value);

} // SubjectExpress
