/**
 * generated by Xtext 2.29.0
 */
package org.xtext.example.mydsl.sparrow;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Subject Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.sparrow.SubjectExpression#getKeyValue <em>Key Value</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.sparrow.SparrowPackage#getSubjectExpression()
 * @model
 * @generated
 */
public interface SubjectExpression extends EObject
{
  /**
   * Returns the value of the '<em><b>Key Value</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.sparrow.keyvalue}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Key Value</em>' containment reference list.
   * @see org.xtext.example.mydsl.sparrow.SparrowPackage#getSubjectExpression_KeyValue()
   * @model containment="true"
   * @generated
   */
  EList<keyvalue> getKeyValue();

} // SubjectExpression
