/**
 * generated by Xtext 2.29.0
 */
package org.xtext.example.mydsl.sparrow;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Time Sub</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.sparrow.TimeSub#getValueA <em>Value A</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.sparrow.TimeSub#getValueB <em>Value B</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.sparrow.TimeSub#getValueC <em>Value C</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.sparrow.TimeSub#getDuration <em>Duration</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.sparrow.TimeSub#getCompare <em>Compare</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.sparrow.SparrowPackage#getTimeSub()
 * @model
 * @generated
 */
public interface TimeSub extends TrueCondition
{
  /**
   * Returns the value of the '<em><b>Value A</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value A</em>' containment reference.
   * @see #setValueA(MixExpression)
   * @see org.xtext.example.mydsl.sparrow.SparrowPackage#getTimeSub_ValueA()
   * @model containment="true"
   * @generated
   */
  MixExpression getValueA();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.sparrow.TimeSub#getValueA <em>Value A</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value A</em>' containment reference.
   * @see #getValueA()
   * @generated
   */
  void setValueA(MixExpression value);

  /**
   * Returns the value of the '<em><b>Value B</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value B</em>' containment reference.
   * @see #setValueB(MixExpression)
   * @see org.xtext.example.mydsl.sparrow.SparrowPackage#getTimeSub_ValueB()
   * @model containment="true"
   * @generated
   */
  MixExpression getValueB();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.sparrow.TimeSub#getValueB <em>Value B</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value B</em>' containment reference.
   * @see #getValueB()
   * @generated
   */
  void setValueB(MixExpression value);

  /**
   * Returns the value of the '<em><b>Value C</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value C</em>' reference.
   * @see #setValueC(RuleExpression)
   * @see org.xtext.example.mydsl.sparrow.SparrowPackage#getTimeSub_ValueC()
   * @model
   * @generated
   */
  RuleExpression getValueC();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.sparrow.TimeSub#getValueC <em>Value C</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value C</em>' reference.
   * @see #getValueC()
   * @generated
   */
  void setValueC(RuleExpression value);

  /**
   * Returns the value of the '<em><b>Duration</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Duration</em>' containment reference.
   * @see #setDuration(Duration)
   * @see org.xtext.example.mydsl.sparrow.SparrowPackage#getTimeSub_Duration()
   * @model containment="true"
   * @generated
   */
  Duration getDuration();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.sparrow.TimeSub#getDuration <em>Duration</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Duration</em>' containment reference.
   * @see #getDuration()
   * @generated
   */
  void setDuration(Duration value);

  /**
   * Returns the value of the '<em><b>Compare</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Compare</em>' attribute.
   * @see #setCompare(String)
   * @see org.xtext.example.mydsl.sparrow.SparrowPackage#getTimeSub_Compare()
   * @model
   * @generated
   */
  String getCompare();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.sparrow.TimeSub#getCompare <em>Compare</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Compare</em>' attribute.
   * @see #getCompare()
   * @generated
   */
  void setCompare(String value);

} // TimeSub
