/*
 * generated by Xtext 2.28.0
 */
package org.xtext.example.mydsl.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.example.sparrow.ui.internal.SparrowActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SparrowExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(SparrowActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		SparrowActivator activator = SparrowActivator.getInstance();
		return activator != null ? activator.getInjector(SparrowActivator.ORG_XTEXT_EXAMPLE_MYDSL_SPARROW) : null;
	}

}
